# Generated by Django 4.0.6 on 2024-02-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_answer_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
    ]
