# Generated by Django 4.0.3 on 2024-02-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_user_verifycode_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verifyCode',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
